### ISSUE TITLE
Calculations by year (previous year especially)

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/VERIFI#100]

**Comment by koay9f** [comment]
I'm not 100% sure this is what this is referring to, so if not, pls open a new issue:
I think the calcs for Previous year are not quite right.  I have two electricity meters, and they are working fine for "Last Month" and "monthly average" but previous year I think is not taking both meters.

![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/dfb0a006-d268-4fdb-a44b-024560992895)

This is from the "dumb data" file where every month is 100 MMBtu of electricity x 2 meters & 200 MMBtu of NG
