### ISSUE TITLE
Overview Carbon Math/Presentation

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/VERIFI#1048]
This is for market based
For tables and graphs - 
1 - group emissions by utility type (not meter)
2 - Reported Market Emissions = sum(meter's market emissions) - sum(meter's excess RECs emissions)

Bonus points (can make this another issue - just let me know if I should be looking for itt):
Area graph - switch between "net" (grouped by utility type) and "meter"
VPPA & RECS "emissions" = -1 x excess RECs emissions (so that it is negative.  & maybe have them be a different color (green?) (they can be a different color for all the area graphs if that would help)

Location based emissions is good. (but if you want to  group them by utility type also to keep things the same that is fine, they just don't get the - excess RECs thing)

**Comment by koay9f** [comment]
[carbon overview overhaul.pptx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdmpjIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bd40807dfaba0b96c9dcc84a1cfe6da994d94820/carbon%20overview%20overhaul.pptx)
Still working on the facility level area graph.

**Comment by rmroot** [comment]
I think this is a duplicate to #1314.

**Comment by koay9f** [comment]
I swear I tried to find it, b/c I thought it would be a duplicate.   Just closed 1314 since this one has more info.  Here's the pic from the other issue.
![image](https://github.com/ORNL-AMO/VERIFI/assets/25389736/68b57b65-b385-4669-b81b-e81a87b4f73a)
