### ISSUE TITLE
Auto grouping "Other"

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/VERIFI#1061]
1 - there are two "Others"
2 - I think one is "Other Energy" and the other is "Other [not energy]", but you can't tell which is which and it leads to data being brought in and not being able to be moved to different energy groups

![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/801f4dba-ba44-4fb9-9c53-77bcbb608b1f)

**Comment by rmroot** [comment]
I don't think this is an issue in develop
