### ISSUE TITLE
Way to update if decline auto update

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/VERIFI#1092]
maybe have the version number be a link?
or something in the about page?
or a special link by the (?) 

![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/b7e52de9-af33-4a63-ab26-81a0a5b696fa)

**Comment by rmroot** [comment]
Autoupdater pop up was not showing up from v0.9.3-beta changes. Fixed that in this issue and added button to top navbar for v0.9.5-beta.
