### ISSUE TITLE
Regression validity check

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/VERIFI#1141]
Variable p-values:
all less than 0.2
*at least one less than 0.1*
I think the second one isn't working

![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/09ab426d-5cbd-4592-9f1f-f02edc4915c4)

**Comment by koay9f** [comment]
Still not quite right.
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/1ce0ea76-ec5e-478c-8231-35db7e938a03)
We don't show the intercept p-value on the screen, is it possible your check is including it by accident (the first one has an intercept of less than 0.1 and the second doesn't?)

This is in West Facility, Office Electricity Regression.

**Comment by rmroot** [comment]
will need to regenerate models to update the notes for them.
