### ISSUE TITLE
If change site/source or energy result unit...

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/VERIFI#1182]
then make the yellow warning "You have changed things" a red warning and deactivate facility summary & account analysis

**Comment by rmroot** [comment]
Enhancements added for this issue:

- lock facility analysis setup options if regression models generated
- lock account analysis setup options if facility items selected
- add messaging to analysis when they are used in other areas of the application
- set selected if analysis item is the only one for that year

**Comment by rmroot** [comment]
Used this issue to fix the disabled "Facility Summary" tab when model selected
