### ISSUE TITLE
Additional Weather Data

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/VERIFI#1183]
Incorporate additional weather data for predictors.

- Monthly average temp
- Monthly average relative humidity
- Monthly total precipitation

**Comment by rmroot** [comment]
Adding Relative Humidity and Dry Bulb Temp. 

Issue #1719 for more weather data

**Comment by koay9f** [comment]
Looks weird to "Create Facility Degree Days" when not doing DD.
Maybe change button to "Create Facility Weather Data" ?

**Comment by rmroot** [comment]
Yeah that is in Chris Feedback issue. 

Bug check: Zip = 54805 check dry bulb temp for 2024
