### ISSUE TITLE
Add Water Type to Meters

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/VERIFI#1199]
add water type to meters. will be used for water reports

**Comment by koay9f** [comment]
_Water_
rename to _Water Intake_
Municipal (Potable)
Municipal (Non-potable)
River/Lake
Ocean/Tide
Ground
Other

_Wastewater_
rename to _Water Discharge_
Municipal Sewer
Third-party disposal
River/Lake
Ocean/Tide
Groundwater
Onsite Disposal
Stormwater to Sewer

**Comment by koay9f** [comment]
_Water Intake_
Municipal (Potable)
Municipal (Non-potable)
Surface Freshwater
Ground Freshwater
Salt Water
Other Freshwater
Rainwater
Externally Recycled Water
Other

**Comment by koay9f** [comment]
template updated
