### ISSUE TITLE
Create Weather Data Bug

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/VERIFI#1216]
bug when creating weather data predictors if no predictors in a facility already exist

**Comment by koay9f** [comment]
Made new facility.
Added in several months of data.
Tried to make a weather predictor.  What now? What if I only want to add one?
**![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/83b97e49-2c0c-4393-9fc4-4efac029e9ef)**

I managed to create two predictors, but cannot seem to actually populate the weather data if creating it here if nothing has ever been there.

I *WAS* able to create them via the weather data tab.

But then, if delete existing weather data (so no more predictors exist but some were there before), then get errors
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/5e370530-b37c-4625-ae37-c976c3bd2273)
