### ISSUE TITLE
Other Utility is buggy

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/VERIFI#1242]
Not sure what all is going on.

When you create, it uses the last site to source that you had, but hides the field (it should always be 1 b/c it is not an energy meter).

Here's my inputs.

![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/c98614ed-a5fa-49a5-9ee8-d05979ea1071)
Here's Monthly data.  It is just showing the last other monthly data that I clicked on
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/48a565b0-9355-4f44-bd12-b63725b7f47d)

I would say wait to do this until we have what we *want* in Other Utility outlined better, but for now, it should at least have the correct cost data in there...

**Comment by rmroot** [comment]
I fixed it so that the other utility data will show up properly with consumption and cost values showing. Not sure how we want to go about incorporating other utility into the rest of the application.

**Comment by rmroot** [comment]
Removed energy units from other utility as an option.
