### ISSUE TITLE
Add Purchased Compressed Air to Other Energy

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/VERIFI#1243]
* If chosen, Collection Unit should be the same as gases (gas volumes {SCF, CCF, kSCF, m3} & energy)
* If using physical unit, need heat capacity. Change name of "Heat Capacity" label to "Specific Energy" (default - 10.93/1000000 MMBtu/ft3) {if we don't do this anywhere else, maybe leave the label change for now }
* Need site to source (default = 3)
* CO2 emission - use electricity 
* gets included with other energy things in better plants report

**Comment by koay9f** [comment]
Template is updated for this

**Comment by rmroot** [comment]
Did not do:
 Change name of "Heat Capacity" label to "Specific Energy"

That is not something we are doing for any other type of meter. Can create new issue if we need to be changing "Heat Capacity" label
