### ISSUE TITLE
Dynamic Fuel Heating Value

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/VERIFI#1244]
Make it so HHV can be dynamic
* add column to template
* add field to "add new bill"
* add checkbox? to meter setup
* do math via data table instead of static

**Comment by rmroot** [comment]
I think issue #1389 takes care of everything but updating the template

**Comment by koay9f** [comment]
Import looks good.
Export Fuel Efficiency is being set with Total Consumption or Total Distance instead of Fuel Efficiency
