### ISSUE TITLE
Analysis Summary report

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/VERIFI#1282]
Simple summary or report somewhere that shows
Facility | Group | Equation (string) | R2 | Adjusted R2 | Model Year

**Comment by koay9f** [comment]
could be tab
Corporate Analysis
Analysis Setup | Select Facility Items | Review Analyses | Analysis Reports

In Review Analysis - table with copy button

**Comment by rmroot** [comment]
There will be two analysis reports. First we need a facility level report and then we will need a corporate analysis report. I am going to work on the facility one and use that with banking.

**Comment by koay9f** [comment]
<img width="1727" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVptQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--44cd4c2e7f60fb068c3a77410cb6e8fe35407300/image.png" alt="image.png" />

header for Incre. Improve. not showing up b/c by default this isnt checked
<img width="1531" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXhtQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d915555b48606c76c052fe1e47044c62917ba115/image.png" alt="image.png" />
