### ISSUE TITLE
RECs fixes

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/VERIFI#1352]
A few fixes for RECs 

1. Total Energy column should be zero if "Include in Energy" is "No" (RECS, VPPAs)
2.  The Excess RECs should be multiplied by the residual mix factor, not location based mix factor
3.  Hide "Excess RECs" EVERYWHERE
4.   Change  "Excess RECs Emissions" to "REC Equivalent Emission Reduction"

Using "Annual" calendarization method
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcWZiIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--35ffcff9392f980997c4ec493764aba698342bf3/image.png)

**Comment by rmroot** [comment]
does this relate to issue #1313 that is in needs verification? Was this from Develop or from the released app?

**Comment by koay9f** [comment]
Yeah, they're kind of connected.  Also kind of connected to the "VERIFI Presentation" overview mockups.
If "Total Energy" was set to be zero for "Include in Energy" = "No" meters, that might solve the #1313 issue, depending on how those are made.
