### ISSUE TITLE
Uploading Meter Data Enhancement

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/VERIFI#1428]
When uploading meter data to a facility with existing data. See if we can add a way to map the data to an existing meter. Currently if the names are not identical then it creates a new meter.

May want same feature for Predictors.

**Comment by rmroot** [comment]
Base on how I implemented this. I don't think it is possible to do Predictors too. Can select an existing meter when editing meter on upload

**Comment by koay9f** [comment]
I'll make a backlog issue for predictors, at some point we may need a predictors epic where we fix a lot of little "it could be betters"
right now, I'm trying this and it is telling me my new data is invalid.
The "first upload" is in sheet 1, the "second upload" is in sheet 2.
The workflow is great, it's just not accepting the data and I can't tell why.
