### ISSUE TITLE
Excel Data Templates

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/VERIFI#149]
Create templates in excel with dropdowns

Template has pages for meter and meter data.

Templates are in src/assets/csv_templates

**Comment by rmroot** [comment]
Source options: 

    "Electricity",
    "Natural Gas",
    "Other Fuels",
    "Other Energy",
    "Water",
    "Waste Water",
    "Other Utility"

**Comment by koay9f** [comment]
[excelTemplateVERIFI.xlsx](https://github.com/ORNL-AMO/VERIFI/files/5992254/excelTemplateVERIFI.xlsx)

password is VERIFI
Dropdowns for:
Source
Collection Unit (dependent on source & phase)
Phase (dependent on source)
Fuel (dependent on source & phase)

so we may want the column order to be ... meter group, phase, fuel, collection unit

The only thing that is not optimal is that "Other energy" will have to have the full list.  I really don't want to do it for each fuel :/

**Comment by koay9f** [comment]
[https://app.zenhub.com/files/252534096/c9e57eec-09c1-4f23-bdb2-7259c369fe1d/download](https://app.zenhub.com/files/252534096/c9e57eec-09c1-4f23-bdb2-7259c369fe1d/download)
