### ISSUE TITLE
Existing & Custom biofuels - biogenic emissions

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/VERIFI#1494]
When showing the calculated emission factor on screen, it should be calculated w/o the CO2 like when you calculate the emissions.

Existing biofuels - Should be listed as such so CO2 is marked as biogenic and not counted
<img width="928" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2k1QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--286bb4fa36520e78584974fef8554ff4cf36f128/image.png" alt="image.png" />

Landfill gas
<img width="515" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1M1QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a48116774b94248afc5418b698f11e382c1d3f97/image.png" alt="image.png" />
<img width="502" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEc1QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2c8a118c6ea64f117ac8fcbc669777f4bb8f6e26/image.png" alt="image.png" />
<img width="1013" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFc1QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4daf479fab1c5b1d45b98ac2e71d652b2e7864b0/image.png" alt="image.png" />

All biofuels
Doesn't look like it is calculating  the  emissions from non CO2 correctly (Extreme example ahead)

<img width="1557" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd201QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1c9a797783339294a5cacb2e661229d0128cf309/image.png" alt="image.png" />

Emissions should be =  10000 x (25x30000/1000 + 298x20000/1000) = 67100 tonne CO2e

**Comment by koay9f** [comment]
Meter Tables for Other Fuels and NG should look more like Mobile emissions (with Biogenic Emissions and Total Emissions instead of Market & Location)
Add new bills for Other Fuels and NG should look more like Mobile emissions for the emissions calcs (with Biogenic Emissions and Total Emissions table instead of "Total Stationary Emissions")
Database fuels need to be labeled as biogenic (see highlighted screenshots above)

**Comment by rmroot** [comment]
List of fuels tagged biofuel after update:

Mobile:
- Ethanol (100%)
- Biodiesel (100%)

Stationary Gas:
- Landfill Gas

Stationary Liquid:
- Ethanol (100%)
- Biodiesel (100%)

Stationary Solid: 
- Peat
- Wood
- Biomass
- Black Liquor

**Comment by rmroot** [comment]
List of fuels tagged biofuel after update:

Mobile:
- Ethanol (100%)
- Biodiesel (100%)

Stationary Gas:
- Landfill Gas

Stationary Liquid:
- Ethanol (100%)
- Biodiesel (100%)

Stationary Solid: 
- Peat
- Wood
- Biomass
- Black Liquor

**Comment by rmroot** [comment]
Natural Gas is not broken down by the different chemical factors at this time. Going to omit the changes for natural gas and just make them for other fuels.
