### ISSUE TITLE
importing from old VERIFI backups has undefined scope - need to set defaults

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/VERIFI#1522]
importing from old VERIFI backups is also causing Natural gas to not have a scope, by default setting to blank, which is being read as "Mobile" so it is asking for a vehicle category and setting it to "Material Transport Onsite"
Can we make it so that Natural Gas & Other Fuels defaults to Scope 1: Stationary if scope is blank?

**Comment by koay9f** [comment]
#1522

**Comment by rmroot** [comment]
This is a bug when importing from an old template exported last year. There is a workaround if this happens again from other users but we are going to choose not to implement logic to support this use case. closing

**Comment by rmroot** [comment]
There was a small bug that I found while testing. Using the v1 template and the wizard would have caused errors. Was using the selected account on upload, not the one setup in the wizard. Fixed.
