### ISSUE TITLE
Weather Predictor Override

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/VERIFI#1548]
Have ability to go into generated weather data and modify entries. Specifically if the data is flagged as calculated with errors.

**Comment by rmroot** [comment]
Weather data entries with errors in calculations have ability to set the values manually and will be given an asterisk.

Updated navigation from predictors to weather data to select facility properly.

**Comment by koay9f** [comment]
second thing - Chris was expecting a pencil button or something instead of just the text link.  I'm not sure how we would want to do that, but I do admit that the text link for this is not very intuitive.
