### ISSUE TITLE
BP report - bugs

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/VERIFI#1624]
1 - is normalization adjustment rounded or something?  displaying rounded number in VERIFI reort
2 - formula for total primary energy not catching all energy types in excel report
3 - also, first year report the new energy savings for current year and total energy savings since BL yr & annual improvement and total improvement should be the same (paired)
see slack conversation with alex

**Comment by rmroot** [comment]
Able to do 1 and 2 for this release. Creating new issue for 3, seems like a bigger math issue.
