### ISSUE TITLE
NAICS code not updating if facility made after account creation

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/VERIFI#1658]
Users created account and facilities via template upload with NAICS code
Did things with VERIFI
Created new facilities, manually set NAICS codes properly, but was not displaying on this table
<img width="1580" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2tOQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--18e458f00e04e94c0c50f7d6751b7a36000137d9/image.png" alt="image.png" />

^ was after I just set the NAICS for each facility in VERIFI & Still blank

**Comment by rmroot** [comment]
There is an issue with the example but this bug has been fixed. Example issue created
