### ISSUE TITLE
quick fix bcc report

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/VERIFI#1666]
this.onSiteGeneratedElectricity = this.getElectricityUse(electricityMeters, year, 2);   - GOOD
this.purchasedElectricity = this.getElectricityUse(electricityMeters, year, undefined); - SHOULD PROBABLY sum of all "include in energy" - this.onSiteGeneratedElectricity
this.gridElectricity = this.getElectricityUse(electricityMeters, year, 1); - WHERE IS THIS GETTING USED. THE LINE FOR GRID ELECTRICITY IS FILLED VIA MATH
this.pppaElectricity = this.getElectricityUse(electricityMeters, year, 3); - THIS SHOULD ALSO INCLUDE "GREEN UTILITY PRODUCT" (5?)
this.vppaElectricity = this.getElectricityUse(electricityMeters, year, 4);  - GOOD
this.RECs = this.getElectricityUse(electricityMeters, year, 6);  - GOOD

**Comment by koay9f** [comment]
also - MWh should be site energy, not source

**Comment by koay9f** [comment]
Discontinuity between Emissions Overview, VERIFI To Excel, and VERIFI BCC report.

quick check of stationary has Overview & Excel as the correct values
I think overview & excel are also correct for the scope 2

**Comment by rmroot** [comment]
I have updated with some fixes. There was a site to source bug in there of emissions but I wasn't able to re-produce the test scenario above. I think your example is missing a facility or something. 

I updated the report math. This should be extensively tested.. 

"Remaining Grid" is in the "Total Energy Use For Portfolio" section of the report and calculated in the excel report by excel.

**Comment by koay9f** [comment]
I was just running a report on "West" facility, but everything looks okay, so I'm going to close for now and I guess we keep an eye out

**Comment by koay9f** [comment]
The math for "remaining grid electricity" should be something like "Total Purchased" - PPPAs - financial - unbundled RECS.
"Total Purchased" = something like grid electricity + PPPAs  (probably this.purchasedEnergy)
