### ISSUE TITLE
Selected Facility shouldn't show on Corporate setup

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/VERIFI#168]
No facility should be selected on the corporate setup form. 

Double check it should be selected in the dashboard for corporate

**Comment by koay9f** [comment]
Is this in develop? 
Cause the facility name is still there ...
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/bd268a7a-33f7-4260-9e9e-280cf2aa1f53)

**Comment by cranfillkd** [comment]
Checked this on both the branch and develop and seems to be working fine.

**Comment by koay9f** [comment]
This bug has Frankenstein-ed.  It is somehow in the release  :sob:

**Comment by cranfillkd** [comment]
Sorry! I misunderstood. This is where I fixed it🤦‍♀️ : We are on the same page now.

![Screen Shot 2021-04-23 at 3.43.03 PM.png](https://images.zenhubusercontent.com/5e00ded53da7a2493c3ff38c/dc7f7a39-dfef-443f-8aef-daede1d5ec2d)
