### ISSUE TITLE
Chris Predictors Feedback

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/VERIFI#1723]
- Filter calculated predictors that have errors
- Have way to set ranges in predictor "bulk management" page that defaults dates to meter ranges
- "Create Degree Days" = "Create Weather Data" on annual page
- Update calculated predictors to latest on upload and meter data additions

**Comment by rmroot** [comment]
Predictor data entries will be generated on creation of predictors for weather.

**Comment by koay9f** [comment]
default bulk update from (latest meter read date - 6 months) to last meter reading
