### ISSUE TITLE
Utility bill: 2 of the same month error handling

### ISSUE THREAD

**Issue by cranfillkd** [ORNL-AMO/VERIFI#20]
-Handle importing conflicts
-Disable months with data already existing

**Comment by koay9f** [comment]
did not flag that these two were repeats

![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/48622413-2e65-4015-8f85-44f78d14c7d9)

I just copied two entries from the "dumb data" excel I've posted in a few issues already (and changed the values to 5000)
