### ISSUE TITLE
Units

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/VERIFI#200]
Heat Capacity Unit Conversion is not working.

I set default energy value to MWh

![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/5d2e6344-1075-445b-b532-fc215d527f03)

The Heat capacity should be
0.001029 (MMBTU/scf) x 0.29307107 (MWh/MMBTU)

EDIT: 
Correction, this is not 100%.  I also tried Propane and it converted just fine.  So maybe it is just a NG thing?

**Comment by koay9f** [comment]
Also, what would happen to the DATA if I change the default energy unit?
I guess it would change the "heat capacity" and it would just go through...

Should we lock a meter's Collection unit once they have data?

**Comment by rmroot** [comment]
Meters collections units are locked if they have data

**Comment by koay9f** [comment]
Excellent.
