### ISSUE TITLE
Bulk Delete and Order Filter Predictors

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/VERIFI#202]
Need to add bulk deleting functionality and ability to sort predictors table by predictor.

**Comment by rmroot** [comment]
Make sure you can add a predictor without any entries

**Comment by koay9f** [comment]
Tried to sort by CDD and this happened.  

![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/5d660521-88c7-4610-9ac7-a1d3e77855c0)

maybe something to do with 2 Predictor3?
