### ISSUE TITLE
Utility Groups: Frac of tot year

### ISSUE THREAD

**Issue by cranfillkd** [ORNL-AMO/VERIFI#22]
Formula is currently total group sum/total meter sum. It needs to be last 12 months and not the total. May have to ping Kristina for the formula again.

**Comment by koay9f** [comment]
Figure out the latest complete year for any given meter (2019, 2018, 2019, 2019)
Figure out the latest year of ^ years (2019)
"Total" = the total from ^ year (#, 0, #, #)
