### ISSUE TITLE
Add new meter in import wizard

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/VERIFI#238]
If you import data from template that doesn't have a meter, it currently just gives a warning and says it will be skipped.

We need more guidance here

1 - literal just guidance: say they can either create a meter back on that page or in the template and reupload the data
2 - Modals within modals: somehow make it so they can create a meter within the modal
3 - forced navigation: auto exit out of modal to the meter page and import remembers what file you were trying to upload?
4 - open to other ideas

**Comment by rmroot** [comment]
This is taken care of with new import setup. closing
