### ISSUE TITLE
Paulomi Smaller things

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/VERIFI#241]
1.	Zipcode in Corporate page needs to be a number input without the up and down button
3.	Have a way  to minimize the Setup Progress but still have it in the page so that it can show where to go next
4.	When you click on the cells to put in values can it become empty rather than making me delete 0?
5.     Site or Source? --> change question to "Energy displayed as site or source?"
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/37c7d281-283a-4ccb-a31c-1aa32affe55d)
10.	 Can we remove the Total Demand if we don’t have data. Keep the Cost column but we do need that Info. (from KOA - Cost should not be "mandatory" but we should leave it in the table to encourage use)
12.	Doesn’t take in Therms Automatically from excel import (from KOA - I think this might be in another issue, but we need to check that the string finder being used will recognize what is in template - either change template or lists)
14.	Other Fuel unit MMBTU doesn’t take in from Excel sheet (from KOA - same thing as 12?)

From KOA:
For import - give error if Site To Source is blank

Important ones:
5, 12, 14 & From KOA

**Comment by rmroot** [comment]
1 - done
2 - skipped (new issue)
3 - Content of cells highlight when clicked now
4 - done
5 - Added total demand option to columns filter (defaults on)
6 - Therms and Dtherms should work for importing
7 - Did some fixes for other fuels. Couldn't recreate MMBtu issue

Site to source validation updated
