### ISSUE TITLE
Abs / Intensity for goals

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/VERIFI#243]
6.	For Goals: Add “absolute” or “intensity” goal  for 1, 2, 5 and maybe 4

From KOA: Radial buttons?

**Comment by cranfillkd** [comment]
@koay9f Can we get a bit more info on this please?

**Comment by koay9f** [comment]
![image](https://user-images.githubusercontent.com/25389736/121191718-381cc500-c83a-11eb-8759-64fa2b580623.png)

Just specifying if the goal is absolute (an X reduction in energy use) or intensity (an X/Y reduction in energy use per production)
For Energy, Carbon, Waste, and water.  Doesn't make sense for renewable energy
