### ISSUE TITLE
Template Units for import

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/VERIFI#276]
Make sure that the units in the template, what import is looking for, and VERIFI dropdowns match.
Figure out which is the "correct" version of each type of unit.

**Comment by cranfillkd** [comment]
@koay9f do you mean ftsq vs ft2 etc?

**Comment by koay9f** [comment]
yeah. but it is more about the template, so MMBTU vs Mmbtu vs MMbtu

I guess this could be an intern issue instead of a me issue...

**Comment by shivasaurus** [comment]
List of inconsistencies:
Natural Gas and Other Fuels (gas): has m^3 in the dropdown vs nm^3 in the template. Has SCF and CCF in the template but does not have them in the dropdown. 

Other Energy Units: has “gal-F” and “ton-hr” in the template but does not have them in the dropdown. 

Other Utility Units: has “gal, m3, L” in template vs. “kwH, mwH, kJ, GJ, MJ, Therms, dTherms, MMBtu, kcal” in dropdown.

**Comment by koay9f** [comment]
"Nm^3" is the same as "m^3", I need to think on if we want the N or not. (I'm asking Tom - I'll update this when I have an answer)

We do need SCF and CCF.  SCF is in the dropdown as "Standard Cubic Feet (SCF)". We need to add CCF to the unit conversion capabilities.  1 CCF = 100 SCF.  Mark can help with this

to find the "Other Energy" units you need to switch "Fuel Type" to one that includes "Purchased Chilled Water". then they should be there

Other utility is an important one.  Honestly, probably both are wrong.  It should have ALL possible units available to it.  I'll fix the template sometime if you can fix the dropdowns

**Comment by koay9f** [comment]
FYI - it needs to be Nm^3. 
more FYI - Nm^3 = m^3 and SCF = ft^3 for the purposes of VERIFI this is just a labels thing
