### ISSUE TITLE
Calendarization - date = MM/01/YYY

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/VERIFI#283]
It looks like we are losing the first & last month even when our meter read dates are the first on the month.  This should still yield 12 full months...

test using an enpi data set

**Comment by rmroot** [comment]
During verification: 

North example meters are set to forward and South is backwards

Defaulting to full month

**Comment by koay9f** [comment]
default works well

For table, maybe show 
meter read date | kWh/day | Calendarized Month

**Comment by koay9f** [comment]
Everything is lovely.  The math looks good. I think the text is understandable. I love the highlighting in the tables.

three things:
1 - Apply to Full Read month --> `Do not calendarize Meter Data` or something similar
2 - help text at top:
`Calendarization is the process of allocating data to a consistent and appropriate use period. This is done for reporting purposes so that there can be a fair comparison of utility data for each year and resource. The standard way to calendarize utility data is to divide consumption for each utility by the number of days on the bill. Usage is then allocated to each month based on this daily use ratio and the number of billing days in each month.`
3 - Don't spend a lot  of time on this one: can we make it so that if you hover over the calendar pic, it does the same highlight thing?  this can be put in the icebox if it takes you more than a few minutes.
