### ISSUE TITLE
Settings Links

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/VERIFI#291]
Add settings link to account settings in sidebar
Remove settings link in footer
Add settings gears to menus in header

**Comment by cranfillkd** [comment]
This is complete other than the sidebar. I thought we decided against that?

**Comment by rmroot** [comment]
sorry for slacking on responding to this. The settings link is still in the footer. I don't 100% recall but believe I made this issue after we discussed. Not sure, may need to discuss again.
