### ISSUE TITLE
Dev-tools key entry

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/VERIFI#293]
For the time being allow the dev tools to be opened (even in production) using ctrl+shft+i like in a typical browser window

**Comment by cranfillkd** [comment]
What do you want in the dev tools? Just the delete database button or others?

**Comment by rmroot** [comment]
I just want the dev tools to be able to be opened with your keyboard in the electron window of a release build

**Comment by cranfillkd** [comment]
The dev tools I created or like the chrome inspect panel

**Comment by rmroot** [comment]
Chrome inspect panel

**Comment by rmroot** [comment]
At least for the time being I'd like to be able to access the console to see any errors in a production build if bugs show up

**Comment by rmroot** [comment]
Dev tools can now be opened with ctrl+i or cmd+i in electron
