### ISSUE TITLE
Where do we need help text

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/VERIFI#300]
Based on user feedback

In places where we talk about site/source but especially on corp/ facility settings pages

via Alex
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/ec7394a9-ffff-4ec2-a8dd-c73cd3f1d363) 
•	I am confused by the language here. 
o	Are the predictors columns that are used to make the model? 
	Does this include the energy sources 
o	Are “meters” if I had a list of meter numbers 
o	Is there sample data for us to see here. Something is not clicking 

I think this confusion would be helped by help text for each of the VERIFI columns (predictors = weather and prod)

**Comment by rmroot** [comment]
Help text issues added, will have field by field help and a panel for general help

**Comment by rmroot** [comment]
closing this issue since it's stale and individual help text issues have been created
