### ISSUE TITLE
Alex comments - utilities - import - dashboard

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/VERIFI#302]
•	why does electricity have "heat capacity" default

![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/d575f2cb-e678-4394-821a-7b02bea7e349)
•	I am confused by the language here. 
o	Are “meters” if I had a list of meter numbers 
o	Is there sample data for us to see here. Something is not clicking 

 
•	I needed biofuel. I think it may be common enough to add
•	My site to source conversion disappeared when I used landfill gas (changed units?)

•	When I was confirming my meter “save and continue” made me think it would go to the dext to fix the error. Possible disable if there are still errors or rename to “confirm all meters” 

 
•	When I add a meter, A warning should pop up or highlight the box if the sit to source conversion changes. (ie, I changed the site to sh=ource THEN changed the units and it reverted back to the default 

•	I didn’t see the template for data until Kristina pointed it out 

•	When switching through utility usage and cost graphs, can you move the toggle closer to the actual graphs, it took me a min to find it

**Comment by rmroot** [comment]
-Don't have an answer for electricity heat capacity

-Added help text blurb for the column mapping

-Updated verbage for "Submit and Continue" to "Submit Meters and Continue"

-Moved Template to center of upload screen

Adding issues for:
-Biofuel
-Site to source warning
-Moving toggle for graphs

**Comment by koay9f** [comment]
- Small thing. Re: conversation yesterday: Maybe in the (very nice) blerb for column mapping add:
`Please use site energy data when possible.` as another blerb.

Everything else is good
- `Don't have an answer for electricity heat capacity`
     - it doesn't seem to be there anymore.  maybe for a while we still had a heat capacity field for electricity meters?
- Template is much more obvious

**Comment by rmroot** [comment]
Additional blurb added.
