### ISSUE TITLE
Canvas Global style

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/VERIFI#307]
There is a canvas global style in style.css with !important properties that end up being applied to some types of plotly charts. It results in having some plot traces that are offset off the main chart. I believe it was used for the confetti, we need to figure out way to make it not global. I have commented it out in the visualization pull request because that is where I found it starting to mess with the charts.

**Comment by rmroot** [comment]
This issue came back as a problem I think. Should handle sooner then later.

The dots on the data correlation plot in visualization tab is off of it's axis

**Comment by koay9f** [comment]
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/8988ec73-7001-46c2-aa3d-65f32c5f2bf6)
