### ISSUE TITLE
More VERIFI review

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/VERIFI#309]
May need to break up
From Chris Price
Add MCF as an option for gas in the import template
In general add more options for importing units into VERIFI
Heat capacity unit for natural gas in the 'import meter tab' is in kWh/SCF? Shouldn't that be something like MMBtu/SCF?
Add PF as a variable to track in the template
Same number of yticks on both charts in the monthly data tab
Cost and usage buttons seem to be flipped in the monthly meter data tab?

**Comment by rmroot** [comment]
Creating issue for:
-Add MCF as an option for gas in the import template
-In general add more options for importing units into VERIFI
-Add PF as a variable to track in the template

**Comment by rmroot** [comment]
Set number of ticks for calanderization to be the same for both y axis's

not sure about "Cost and usage buttons seem to be flipped in the monthly meter data tab?"

**Comment by koay9f** [comment]
-  `not sure about "Cost and usage buttons seem to be flipped in the monthly meter data tab?"`
     - Maybe the graphs?  They seem to be fine now...
- number of ticks - check
