### ISSUE TITLE
VERIFI Error check - multiple meter reads per month

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/VERIFI#338]
Maybe make multiple meter reads per month a yellow issue or something you can dismiss?
It is possible that you could have a meter read at the beginning of the month and at the end of your utility really kind of sucks

**Comment by koay9f** [comment]
Okay this extends to calendarization...
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/3da8d38b-0d17-4882-80b6-db413e275a92)
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/77c917e9-115c-44f6-9ff8-6e2bbf8d7e4c)

**Comment by rmroot** [comment]
Figure out a way for the above scenario to recognize the Nov 2 entry should be applied to October 2020

**Comment by rmroot** [comment]
Calanderizing works for more then one reading in a month and months without readings.

If you choose not to calanderize, more then one reading in month will just be added together

**Comment by koay9f** [comment]
Visually everything looks good.  Still checking math

still would be good if we had non-stopping error messaging for 
* two meters in one month
* the bills on either side of a missing month

maybe just red font and a pop up or message  that you can "acknowledge" and close.
