### ISSUE TITLE
Results Rounding

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/VERIFI#342]
Add rounding/sigfigs for result values

Ex - heat capacity after unit conversions
Ex - Calendarized data

Would be best if we  could only do it for display and keep the full values for calculations. If that's not easily possible, then we may want to pick and choose more where we do this or just keep A LOT of sig figs (5 - 6)

**Comment by rmroot** [comment]
After discussion it was decided that: 

if display value is < 10000 then rounds to max 5 sig figs
if display value is > 10000 then removes decimals
