### ISSUE TITLE
Address ansi-html

### ISSUE THREAD

**Issue by gaccawi** [ORNL-AMO/VERIFI#371]
ansi-html

**Comment by rmroot** [comment]
comes from webpack-dev-server a dependency of @angular-devkit/build-angular

**Comment by rmroot** [comment]
https://stackoverflow.com/questions/69548370/how-to-override-a-nested-npm-sub-dependency-with-a-different-package-altogether/69591894#69591894

might help.. 

Ultimately upgrading angular 13 will probably be the best solution

**Comment by rmroot** [comment]
Upgraded to angular 13, will need to `npm install` and be using node v 12.20
