### ISSUE TITLE
Unit changes. Update meters.

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/VERIFI#381]
When a user updates their units in the settings we should provide a way to update/convert the meter data

**Comment by koay9f** [comment]
A few problems here now.
Set up everything using kWh and MMBtu (electricity and natural gas). everything looked good.
Switched energy unit to kcal (so would be really different)
emissions factors are still in per kWh & MMBtu, but being multiplied to kcal value

Probably need to have the math for emissions look something like this
emissions = monthly energy  * emission factor * {conversion from monthly energy unit to utility energy unit}
or have a hidden column that is the energy in the original unit still and use it for math
That one might be better b/c Chris mentioned being able to switch between the two would be nice.

**Comment by koay9f** [comment]
nope still a problem
Example East in MMBTU (calendarized)
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/3063cce9-3f3d-4809-acc0-386240eaa653)



Example East in kcal (calendarized)
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/232a20fc-0031-4628-8459-b1614f8d7258)

**Comment by rmroot** [comment]
Forgot I also had to convert electricity. Should be good now
