### ISSUE TITLE
Report #1

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/VERIFI#396]
Setup initial reporting infrastructure for creating reports on the dashboard for accounts and facilities

- Add "Production" checkbox to predictors for energy intensity
- Options for facility and account reports
- Graphs and tables for emissions, cost and energy usage/intensity

**Comment by koay9f** [comment]
Graph/Table Suggestions:
All of these could be added to the dashboards if we can make it tidy

This
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/ead62a5e-500b-4169-8e01-aee4343ed344)

Something like this but "past 12 months" and "previous 12 months" (no average)
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/d3ae478c-aa48-4717-a7e3-068f56b09748)

These (maybe both just latest year)
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/1a8064bf-d20b-4fde-bd3a-0c6e81967d40)

not This:
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/99bc62ca-0236-405a-888a-d5e3d0dee287)

one like this, but aggregate facilities
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/d7826f45-29ed-49e1-83ed-aa60f5e4c581)

FOR FACILITIES - all these for each facility
these
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/4b30427d-1e76-4258-b1de-94020470003c)
+ all the graphs that are in dashboard

I'll let you know if  I think of anything else

**Comment by rmroot** [comment]
Energy Intensity = Energy Use / Production
