### ISSUE TITLE
Report Printing

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/VERIFI#424]
Add ability to print report

**Comment by koay9f** [comment]
There is a button, and it goes through the motions, but the final pdf is all kinds of messed up.  [https://app.zenhub.com/files/252534096/b548eb66-3654-42e9-9c01-4f1ed1b3cdda/download](https://app.zenhub.com/files/252534096/b548eb66-3654-42e9-9c01-4f1ed1b3cdda/download)

**Comment by koay9f** [comment]
It prints, but need to be careful with graphs going across pages
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/444540f2-56e4-4c6a-8284-c580a5db142e)
