### ISSUE TITLE
Help Text Panel: Energy Consumption

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/VERIFI#439]
Fill out help text panel for energy consumption (meters and utility bill pages)

**Comment by koay9f** [comment]
[https://app.zenhub.com/files/252534096/7cc92ba4-f385-420d-9235-0fe56915ff9d/download](https://app.zenhub.com/files/252534096/7cc92ba4-f385-420d-9235-0fe56915ff9d/download)

**Comment by rmroot** [comment]
added help text in

https://github.com/ORNL-AMO/VERIFI/pull/1118

still need help text for Agreement type and other fields.
