### ISSUE TITLE
Help Text Panel: Predictors

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/VERIFI#442]
Fill out help text panel for predictors (predictors-data-help component)

**Comment by koay9f** [comment]
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/56bc24dd-f0ee-4bbb-b900-f6788cb321bf)
Draw attention to
Adding new
Importing
Edit preditors
copy/delete

**Comment by pricecr** [comment]
Consider changing "+ Add Predictor Entry" to just "+ Add New Entry".
[Manage Predictors.docx](https://github.com/ORNL-AMO/VERIFI/files/8891663/Manage.Predictors.docx)

**Comment by JL102** [comment]
Note: Using fa-check-circle for the "predictor is a production item" because that's what was already put into the help text; but it doesn't seem to be implemented yet, so I don't know what icon it is actually going to be.
