### ISSUE TITLE
Help Text Panel: Facility Overview

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/VERIFI#446]
Fill out help text panel for facility dashboard (facility-overview-help component)

**Comment by koay9f** [comment]
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/27c3dbcb-1383-407d-80d0-16f40a35a5b1)
mostly same idea as account dashboard

**Comment by rmroot** [comment]
help text added in 
https://github.com/ORNL-AMO/VERIFI/pull/1118
