### ISSUE TITLE
Help Text Panel: Account Management

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/VERIFI#447]
Fill out help text panel for Account Management (settings) page (account-help component)

**Comment by rmroot** [comment]
this help text taken care of in 

https://github.com/ORNL-AMO/VERIFI/pull/1118

lots of content on this page, hard to balance help text for everything and having stuff buried. Open to suggestions

**Comment by koay9f** [comment]
See the facility account settings.  the suggested changes there are needed here.  Everything else is okay for now.
