### ISSUE TITLE
Small Issues for UI Revamp

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/VERIFI#513]
Give it a bit before starting this.  May be more later

- [x] Side bar - Analysis should be before report
- [x] Year dropdowns - start/default in "past"  maybe initial default be "this year"?  
- [x] Settings energy unit default = MMBTU

**Comment by rmroot** [comment]
From issue #525
Baseline year initialized to this year when account/facility are created.

Report year left undefined.
