### ISSUE TITLE
Chris quick fixes

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/VERIFI#525]
* Can baseline year (for goals) default to "this year"
* In meter setup - `Next Meter` button (instead of `Submit Meter & Continue`, except when on the last one)
* In meter setup - predictors, make checkboxes bigger
* Graphs for predictors page (predictors vs time - the bar charts)
* Analysis - need `Next` button
* FAcility summary monthly analysis bar chart (the one with some with adjusted alphas) - the outline should not have it's alpha adjusted

**Comment by rmroot** [comment]
First 3 done.

Need to discuss second 3

**Comment by rmroot** [comment]
"Facility summary analysis bar chart" not a thing anymore

Predictors graphs can be made in visualization area. Potentially add later

New Issue for next navigation in analysis
