### ISSUE TITLE
Functioning Search Bar

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/VERIFI#553]
add search bar that works for navigating to different areas of the application (meters, grouping, analysis, reports etc..)

**Comment by koay9f** [comment]
idea:
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/d71d4830-f1e8-4dfd-89af-0b77687452de)

**Comment by rmroot** [comment]
Search bar added to navigate to items within selected account:
- Facilities
- Meter Readings
- Account Analysis Items
- Facility Analysis Items
- Reports
