### ISSUE TITLE
Help Text Panel: Setup Account Wizard

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/VERIFI#601]
Help text for account setup found under "Add New Account" or initial starting of the app without data

**Comment by koay9f** [comment]
sorry, too lazy to make a screenshot for this one. Make a new account and just mention what you think is important.  The indivdual pages will have their own help text

**Comment by paulominandy27** [comment]
Welcome to VERFI. In this page you can setup your account details, setup individual facilities that are included in your account and start tracking your energy use. 
Use "Load our teat data" to load test data into VERIFI. 
If you have previously used VERIFI and have your account and facility information exported as *file format name* from VERIFI please use " Load Account Backup" to load your Account information.

**Comment by rmroot** [comment]
tooltips for default units. (Volume unused if no volume meters.. etc)
