### ISSUE TITLE
Help Text Panel: Better Plants Report

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/VERIFI#602]
help text for the better plants report menu and actual report

**Comment by koay9f** [comment]
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/c0f32424-a362-48f9-bffa-61cc268463f6)

I guess just explain what it is for?

**Comment by pricecr** [comment]
See document for issue #608

**Comment by rmroot** [comment]
Most of this issue was taken care of in

https://github.com/ORNL-AMO/VERIFI/pull/1118
