### ISSUE TITLE
Help Text Tooltips: Better Plants Report Setup

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/VERIFI#608]
tooltips for inputs on the better plants options page

**Comment by koay9f** [comment]
KEEP IT SHORT
If you think it needs an explaination, write it

**Comment by pricecr** [comment]
[Better Plants Report Setup.docx](https://github.com/ORNL-AMO/VERIFI/files/8882129/Better.Plants.Report.Setup.docx)

Is there any way to make it clearer that setting the report year in the drop down list is what filters the analysis selection?
