### ISSUE TITLE
Page flow when import account

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/VERIFI#614]
Option to import takes you to the "you have no data page" (which is kind of confusing so maybe a seperate but similar page?)
But mostly it stays there after you complete the import and doesn't give much guidance on where to go next 
Hitting continue makes a new account, but I get no confirmation that the import worked and it should probably take you to the new accounts dashboard or setup

**Comment by rmroot** [comment]
I don't think this is an issue anymore after importing and account setup re-work
