### ISSUE TITLE
Define a working dashboard

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/VERIFI#65]
-What information do we want on the dashboard and what's it going to look like?

**Comment by koay9f** [comment]
Roll ups.  

Boring things like stacked bars where the colors are the facilites, the y = different energy uses and x = months. one for "this year" and one for "last year".

That sort of thing.  We have some examples

Here's one. @paulominandy27 do we have any others handy?
[https://app.zenhub.com/files/252534096/4027b6d2-0cd1-4f11-96c6-ffc14f00be26/download](https://app.zen.hub.com/files/252534096/4027b6d2-0cd1-4f11-96c6-ffc14f00be26/download)

**Comment by koay9f** [comment]
Examples:
https://www.energycap.com/resources/dashboards

https://www.energycap.com/software/energy-use-intensity
https://www.energycap.com/software/calendarization
https://www.energycap.com/software/weather-data
https://www.energycap.com/software/normalization

**Comment by rmroot** [comment]
Setup dashboard components for facility and account. Include components for no account added and no facility selected
