### ISSUE TITLE
Emission Rates for Electricity

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/VERIFI#650]
Setup: Need to show two: Market based and location based
Display (graphs/tables): only show one but have switch like site/source to change which is displayed
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/f5379953-6fde-4806-9815-87f2624a7b01)

Two lookups:
Location based - uses data set currently in VERIFI. user CANNOT override
Market based - new "residual mix" data set. working on it.  User CAN override this one
These will also be time series. so if user enters custom market based emissions, they also need to enter a year for it

**Comment by rmroot** [comment]
Use this issue for applying multipliers when ready.

![image.png](https://images.zenhubusercontent.com/5c9d19352250f9495b573154/4ca79e5f-74a4-4895-a204-65ce022121bd)

**Comment by rmroot** [comment]
Above table is unused.

Updated excel document with emissions factors for location and market based values needs to be added.

Includes years in data and will be used in correspondence with reading dates

Need new issue for creating a database to hold custom user values
