### ISSUE TITLE
Add "Scope" to Meters

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/VERIFI#663]
Scope 1: Stationary
Scope 1: Mobile
Scope 2: Purchased Electricity
Scope 2: Other

**Comment by koay9f** [comment]
I f this is covered in #693 then just close this
Need to confirm with Paulomi...
we mentioned in a call that Electricity should only have "Scope 2" as an option
NG & Other Fuels are the two  "Scope 1" options only
Other Energy is Scope 2: other, but should probably have all 4 just in case.

I think you have those as the defaults, but I think Paulomi was wanting to limit the options

**Comment by koay9f** [comment]
The last comment doesn't seem to be in there
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/12ee4178-aaf2-4b5c-8aef-5078a7ad984f)
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/4a3d860e-ffe2-4424-9f49-c45674b59f92)
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/021dd02d-8429-46bb-91aa-d6acfc4face6)
