### ISSUE TITLE
Account Home Content

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/VERIFI#686]
Come up with what content we want in the account home page

Avoid calculations in this page. Focus on status of the application like things that need to be done like readings, analysis, reports etc.

- Reports
- Analysis

**Comment by koay9f** [comment]
I appreciate the avoiding calcualtions.  
I think as we add more we'll change what we want here, but for now good.
Biggest problem I'm seeing right now is a lot of white space b/c everything in teh card is the full card width.  Is there a way to break that in half? might be nice when we have more things.
