### ISSUE TITLE
Update meter data forms/tables with new fields

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/VERIFI#727]
Fields have been changed for meter data with import changes. Tables and forms need to be updated.

**Comment by rmroot** [comment]
Use this issue for grouping new fields

**Comment by pricecr** [comment]
Talked with Kristina and this is what we came up with. Needs some rearranging of the columns for electricity.
[VERIFI-Import-Data v20220817-GroupNames.xlsx](https://github.com/ORNL-AMO/VERIFI/files/9567258/VERIFI-Import-Data.v20220817-GroupNames.xlsx)
