### ISSUE TITLE
Electricity Agreement type options restrictions

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/VERIFI#803]
Grid can NOT have RECS - make this stronger than default. Even if template has "Grid" and "Retain RECS"
RECS can NOT include energy - ditto
VPPA can NOT include energy - ditto
Grid MUST HAVE Include in Energy - ditto
Utility Green Product MUST HAVE Retain RECS & Include in Energy - ditto

Remove the toggles like "direct connection"

Kristina - fix template
Mark - upload yet another new template

**Comment by koay9f** [comment]
Until someone says otherwise...
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/b82faeb2-2fd3-40a6-911b-53c290f682e4)

**Comment by rmroot** [comment]
created new issue for template update
