### ISSUE TITLE
Fiscal Year Review

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/VERIFI#815]
Make sure all graphs and whatnot work properly using fiscal year data

**Comment by koay9f** [comment]
[PPTX_VERIFI_FY_Issues.pptx](https://github.com/ORNL-AMO/VERIFI/files/9984721/PPTX_VERIFI_FY_Issues.pptx)

**Comment by koay9f** [comment]
looks good. will wait for confirmation from Chris before closing

**Comment by rmroot** [comment]
Check FY math for BP report

**Comment by rmroot** [comment]
FY check predictor variables
