### ISSUE TITLE
Import/export bugs

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/VERIFI#840]
1 - States are not importing properly from template
2 - zips that start with 0 show up as 4 - digit numbers in excel and get imported badly
A- highlight the zip code column in the template. change to "text", make sure imports okay
B - if only 4 digits, assume it starts with 0?

**Comment by rmroot** [comment]
check dates importing/exporting, UTC strings are causing problems when exporting and then re-importing. Especially for dates on first of the month

**Comment by rmroot** [comment]
Add prompt when no calanderization method has been selected

**Comment by koay9f** [comment]
[https://app.zenhub.com/files/252534096/aa724c4f-45cc-4685-b402-a99b4c803cf9/download](https://app.zenhub.com/files/252534096/aa724c4f-45cc-4685-b402-a99b4c803cf9/download)
