### ISSUE TITLE
Mass upload

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/VERIFI#86]
Would be nice to be able to do a bulk upload.

Idea - a company with 30+ facilities would have probably 2 - 4 bills/meters (or more) to add each month for each facility.

Would really suck to have to go to each facility, to each meter type and upload one at a time for these people

So a bulk upload at the corporate or facility level would be really really handy.

Does not have to be implemented anytime soon, but wanted to put it out there in case it would be easier to do earlier.

**Comment by rmroot** [comment]
completed #725
