### ISSUE TITLE
Heat Capacity Unit conversion

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/VERIFI#874]
unit conversion for natural gas is incorrect. Needs to be:

`     
let convertedHeatCapacity: number = this.convertUnitsService.value(.001029).from('MMBtu').to(meterEnergyUnit);

let conversionHelper: number = this.convertUnitsService.value(1).from('ft3').to(startingUnit);

heatCapacity = (convertedHeatCapacity / conversionHelper);
`

**Comment by rmroot** [comment]
meter values are overwriting when uploading data

**Comment by koay9f** [comment]
Looks like this is still off

![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/b98a8a86-0d1b-4414-825d-8e95abd6e16c)
It looks like the math you have above is good and it converts from SCF to CCF correctly, so I'd check the conversion between ft3 and m3

I'm betting that it is that "Nm3" isn't in the unit converter's list (m3 is, but not Nm3) and it is maybe finding the closest thing, which is either a density or volumetric energy value (those are the only ones with "Nm3")
But I can't confirm that. 

I can't test the overriding at the moment.  will get back to you

**Comment by rmroot** [comment]
somehow the fixes for this didn't get in. Connected to the wrong issue PR. Fixed now

**Comment by koay9f** [comment]
I think the conversion to m3 is working, but there is another unit conversion bug in todo, waiting until both are done to fully test.
