### ISSUE TITLE
Button Styling Consistency

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/VERIFI#903]
Make sure button styling is consistent throughout the application for the actions that they do

**Comment by rmroot** [comment]
Also make sure popups have background div to prevent clicking content when popup is open

**Comment by koay9f** [comment]
Not sure entirely about testing this one, so just kind of winging it.

First popup I found, I could click "Import Backup File" while this was open
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/40a2df18-578c-432d-aec5-f9e8602740a2)

I'm having problems finding popups... The "Are you sure" for import start over works correctly
Buttons look good.  Do you remember any other popups that I can test when you fix the one I found?

**Comment by rmroot** [comment]
Good catch. Other places would be like confirming delete of meters/analysis etc.
