### ISSUE TITLE
Toggle Button Confusion

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/VERIFI#928]
Toggle buttons - I know we talked about this once, but it is still hard to tell what is what
Maybe also bold-face the one selected?

![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/686e8609-b10c-4ee8-807b-92c2f3e3cfa9)
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/b686d9da-9f28-45ed-bd26-7628c547ffac)
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/88fcee93-4e5e-4f81-ad87-69de00c9e14b)

**Comment by rmroot** [comment]
fixed in bootstrap update
