### ISSUE TITLE
FY in Overview 

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/VERIFI#950]
Make it so overview is based on FY, not CY
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/930dcb14-434c-4d65-ad9a-5c9f92c55a0f)

EDIT: if these are *Last 12 months* and not last complete year, just make a note and let's discuss with teh group what we want to see

**Comment by rmroot** [comment]
This is just the last 12 months of bills entered. Can scroll the x axis to see more historical data

**Comment by rmroot** [comment]
Don't think this is an issue after overview changes.
