### ISSUE TITLE
Change analysis baseline year

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/VERIFI#967]
Allow users to change baseline year

If Analysis BL =/= Corporate (or maybe Facility) then....
* Warning message "This baseline year does not match your corporate baseline year. This analysis cannot be included in reports or figures relating to the corporate energy goal"
* Link in warning to Corporate / settings page

Checkbox -
"This is a new facility"
If checked, and BL is different from corporate then that is okay. 
Will automatically make a baseline adjustment = baseline year's total energy
@pricecr  - double check that this part makes sense

**Comment by rmroot** [comment]
I have completed the part that allows the user to set the baseline year in analysis and gives a warning about mismatch from goals. 

I did no do the part with the checkbox and baseline adjustment stuff.

**Comment by koay9f** [comment]
95% good
Warning does not trigger if using calendarization (i.e., you have 1 utility bill in the corporate BL year). Can this check be based of meter data instead of bill data?
See Example North Facility for checking (right now North Facility does not get the warning message)
