### ISSUE TITLE
Different BL years

### ISSUE THREAD

**Issue by koay9f** [ORNL-AMO/VERIFI#990]
What is going on if different facilities have different baseline years?
This probably ties in with #967 but need to make sure it is essentially not doing something wrong in the mean time.

**Comment by rmroot** [comment]
Have completed #967. Let me know if there is something else that needs to be done for this issue

**Comment by koay9f** [comment]
We need to change the order of the error checking a bit.
I think we need to be able to see the Analysis setup page so we can change the BL year there, but this error still shows up until you change the baseline year in the form.
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/6b2c89a8-5374-49f8-8891-9f10d795964d)

Re: checkbox -
Add a checkbox between BL year & report year if BL year =/= the goals baseline year.
If that checkbox is NOT checked, then error message "Your baseline year is different from your goal baseline year. Please check this box if it is a new facility" or something like that
If checkbox IS checked, then no message.
ALSO - if possible
If checkbox is checked then the analysis would show up in a corporate analysis as an option for that facility for any year where the corporate BL was less than that facility's analysis baseline.
Add filter to corporate analysis where, like report year, it only shows analyses with the same baseline year (unless checkbox...)

Summary in a different order:
* Account analysis has two errors relating to BL years
 - 1 - You don't have data for all your year, change your BL. This will stop the user from proceeding.
 - 2 - Your baseline is different from your account BL, check the box. This will NOT stop the user from proceeding (but will filter out the analysis from others with different baseline years)

**Comment by koay9f** [comment]
95% good
Warning does not trigger if using calendarization (i.e., you have 1 utility bill in the corporate BL year). Can this check be based of meter data instead of bill data?
See Example North Facility for checking (right now North Facility does not get the warning message)
