### ISSUE TITLE
Sync y axis lines

### ISSUE THREAD

**Issue by rmroot** [ORNL-AMO/VERIFI#997]
https://github.com/plotly/plotly.js/releases/tag/v2.18.0

add sync to graphs with multiple y axis

**Comment by rmroot** [comment]
npm install

**Comment by koay9f** [comment]
Missed one
![image.png](https://images.zenhubusercontent.com/5cd48a2af8cffa5a19122d27/7bf98392-9258-4133-96bc-bdf304408c16)
